//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Purchase = new HashSet<Purchase>();
        }
    
        public string VendorCode { get; set; }
        public string Name { get; set; }
        public int CategoryID { get; set; }
        public int ManufacturerCountryID { get; set; }
        public string ProductCode { get; set; }
        public short InStock { get; set; }
        public decimal HeightCM { get; set; }
        public decimal WidthCM { get; set; }
        public decimal LengthCM { get; set; }
        public decimal Price { get; set; }
        public decimal WeightKG { get; set; }
        public string Description { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}
