//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public string ProductVendorCode { get; set; }
        public int ClientID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public byte Amount { get; set; }
        public int PurchaseStatusID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual PurchaseStatus PurchaseStatus { get; set; }
    }
}
